### ISSUE TITLE
For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.

### ISSUE THREAD

**Issue by Gutek** [globalpayments/dotnet-sdk#11]
Latest (Beta) version of global payments:

```
<package id="GlobalPayments.Api" version="1.6.1-BETA" targetFramework="net472" />
```

Throws:
```
For security reasons DTD is prohibited in this XML document. To enable DTD processing set the DtdProcessing property on XmlReaderSettings to Parse and pass the settings into XmlReader.Create method.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at GlobalPayments.Api.Utils.ElementTree..ctor(String xml)
   at GlobalPayments.Api.Gateways.RealexConnector.MapResponse(String rawResponse, List`1 acceptedCodes)
   at GlobalPayments.Api.Gateways.RealexConnector.ProcessAuthorization(AuthorizationBuilder builder)
   at GlobalPayments.Api.Builders.AuthorizationBuilder.Execute(String configName)
   at CardPayments.Controllers.HomeController.ProcessPayment(OrderDetails details) in D:\tests\GlobalPayments\CardPayments\Controllers\HomeController.cs:line 86
   at lambda_method(Closure , ControllerBase , Object[] )
   at System.Web.Mvc.ActionMethodDispatcher.Execute(ControllerBase controller, Object[] parameters)
   at System.Web.Mvc.ReflectedActionDescriptor.Execute(ControllerContext controllerContext, IDictionary`2 parameters)
   at System.Web.Mvc.ControllerActionInvoker.InvokeActionMethod(ControllerContext controllerContext, ActionDescriptor actionDescriptor, IDictionary`2 parameters)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c.<BeginInvokeSynchronousActionMethod>b__9_0(IAsyncResult asyncResult, ActionInvocation innerInvokeState)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`2.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
```

this needs to be fixed inside lib. as Master is not building I can't do PR.

**Comment by 26Dev** [comment]
I'm also getting this error on the following code when trying to do a transaction release that was on hold:


`// configure client & request settings
ServicesContainer.ConfigureService(new GatewayConfig
{
        MerchantId = "MerchantId",
        AccountId = "internet",
        SharedSecret = "secret",
        ServiceUrl = "https://api.sandbox.realexpayments.com/epage-remote.cgi"
});

// a release request requires the original order id
var orderId = "QAhN4YFrJEWP6Vc-N68u-w";
// and the payments reference (pasref) from the authorization response
var paymentsReference = "15113583374071921";
// create the release transaction object
var transaction = Transaction.FromId(paymentsReference, orderId);

// send the release request, we can choose to specify a reason why we're releasing it
        var response = transaction.Release()
                       .WithReasonCode(ReasonCode.FALSEPOSITIVE)
                       .Execute();`

**Comment by JamieG** [comment]
I'm also receiving this error when trying to execute a charge, I've attempted to pull the master branch to see if I could fix but it's full of class duplications and does not build? Is this code base still maintained?

**Comment by Yubing325** [comment]
is there any fix for this or work arround

**Comment by djcolonico** [comment]
Hi. I'm getting this issue, did anyone manage to fix it?

**Comment by badrshs** [comment]
@djcolonico just use different endpoint, it's https://api.sandbox.realexpayments.com/epage-remote.cgi 

which one you are using ?
