### ISSUE TITLE
Could not load file or assembly 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592'. The system cannot find the file specified.

### ISSUE THREAD

**Issue by adrian-ghibaor-ddroidd** [globalpayments/dotnet-sdk#74]
I am working on a project with Umbraco CMS, and my application will not start when i add GlobalPayments.Api to the project.
I am getting this error:

Could not load file or assembly 'CoreCompat.System.Drawing, Version=1.0.0.0, Culture=neutral, PublicKeyToken=c0a7ed9c2333b592'. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly.InternalLoad(AssemblyName assemblyName, StackCrawlMark& stackMark, AssemblyLoadContext assemblyLoadContext, RuntimeAssembly requestingAssembly, Boolean throwOnFileNotFound)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.<GetReferences>d__8.MoveNext()
   at Umbraco.Cms.Core.Composing.ReferenceResolver.Resolve(Assembly assembly)
   at Umbraco.Cms.Core.Composing.ReferenceResolver.ResolveAssemblies()
   at Umbraco.Cms.Core.Composing.FindAssembliesWithReferencesTo.Find()
   at Umbraco.Cms.Core.Composing.DefaultUmbracoAssemblyProvider.get_Assemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetAllAssemblies()
   at Umbraco.Cms.Core.Composing.TypeFinder.GetFilteredAssemblies(IEnumerable`1 excludeFromResults, String[] exclusionFilter)
   at Umbraco.Cms.Core.Composing.TypeFinder.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.get_AssembliesToScan()
   at Umbraco.Cms.Core.Composing.TypeLoader.<>c__DisplayClass21_0`1.<GetTypes>b__0()
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternalLocked(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypesInternal(Type baseType, Type attributeType, Func`1 finder, String action, Boolean cache)
   at Umbraco.Cms.Core.Composing.TypeLoader.GetTypes[T](Boolean cache, IEnumerable`1 specificAssemblies)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilderExtensions.AddAllCoreCollectionBuilders(IUmbracoBuilder builder)
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder.AddCoreServices()
   at Umbraco.Cms.Core.DependencyInjection.UmbracoBuilder..ctor(IServiceCollection services, IConfiguration config, TypeLoader typeLoader, ILoggerFactory loggerFactory, IProfiler profiler, AppCaches appCaches, IHostingEnvironment hostingEnvironment)
   at Umbraco.Extensions.UmbracoBuilderExtensions.AddUmbraco(IServiceCollection services, IWebHostEnvironment webHostEnvironment, IConfiguration config)
   at CamiraFabrics.Umbraco.Startup.ConfigureServices(IServiceCollection services) in C:\Users\AdrianGhibaor\source\repos\camira-fabrics-umbraco\CamiraFabricsUmbraco\CamiraFabrics.Umbraco\Startup.cs:line 21
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass14_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.InitializeServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Umbraco.Cms.Web.Common.Hosting.UmbracoHostBuilderDecorator.Build()
   at CamiraFabrics.Umbraco.Program.Main(String[] args) in C:\Users\AdrianGhibaor\source\repos\camira-fabrics-umbraco\CamiraFabricsUmbraco\CamiraFabrics.Umbraco\Program.cs:line 6

**Comment by TBeblar** [comment]
There's no need to use CoreCompat.System.Drawing anymore. In fact, the author [says you shouldn't](https://stackoverflow.com/a/47208937/3181933). The reason? Microsoft provides an official System.Drawing.Common NuGet package now.

https://stackoverflow.com/questions/46722409/cannot-find-bitmap-class-in-class-library-net-standard/47208937#47208937

**Comment by SneyderOspinaChavarria** [comment]
Could you try with the version 8.0.5?
It already has the necessary dependencies included in the packages.
https://www.nuget.org/packages/GlobalPayments.Api/8.0.5

**Comment by SneyderOspinaChavarria** [comment]
Doing a test of concept I found that to allow install the GlobalPayments.Api library, you must install first the library CoreCompat.System.Drawing, even, if you are using the another one System.Drawing.Common, and when it has been installed successfully you can install the GlobalPayments.Api library without any issue.
If this is not installed before, at the moment you try to install or update GP library, you will receive an error like this: "Unable to resolve dependency 'CoreCompat.System.Drawing'. Source(s) used: 'nuget.org', 'Microsoft Visual Studio Offline Packages'."

![image](https://github.com/globalpayments/dotnet-sdk/assets/119604937/beed95c7-3cde-4b60-8210-39c7a042f865)

**Comment by adrian-ghibaor-ddroidd** [comment]
Hi, thanks for the responses. This is no longer needed , the client dropped Global Payment on project that i was working on.
